### ISSUE TITLE
baseline results

### ISSUE THREAD

**Issue by yiminglin-ai** [alversafa/chokepoint-bbs#1]
Hi Safa and Ugur,
Thank you for open-sourcing the annotations for the chokepoint dataset. 
I am wondering if you can also provide your evaluation results, such as the tracking results of IVT, GOTURN and AFTN in the text format? This would allow us to perform some comparisons between different trackers on this dataset. Many thanks.
Best regards,
Yiming

**Comment by alversafa** [comment]
(Added to the repo.)
